### ISSUE TITLE
incorrect relevant span mapping

### ISSUE THREAD

**Issue by Narabzad** [Yale-LILY/QMSum#4]
Hi,

Thank you for the great work, 
There are some problems with the dataset and the extracted relevant spans.
For example in Bmr023.json#L39
for the query "What was decided on DARPA?" the relevant spans is annotated as turn 32-35 but actually it is 36-39.

Is there problem with mapping? or should I count the turns in another way?

**Comment by maszhongming** [comment]
Thank you for your interest in our work!

I looked at the example you gave, and I'm sorry that this is indeed a relatively poor-quality answer. There are many annotators involved in the construction of QMSum, it is inevitable that the quality of a few answers may be relatively poor. But based on the relevant text span, this answer can actually be obtained, because the main information is in Turn 35 (Turn's index starts from 0). Have you found more examples of mismatches? I will take a closer look at them to find out if some annotators have misunderstood the index of the utterance.

**Comment by Narabzad** [comment]
okay! makes more sense now.
Thank you for the clarification
